### ISSUE TITLE
Undefined index: HTTP_HOST in WP CLI

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#88]
I get a PHP error when running `wp core language install de_DE`

`PHP Notice:  Undefined index: HTTP_HOST in /polylang-pro/include/links-domain.php on line 73`

Running Polylang 2.1.

**Comment by Chouby** [comment]
This line is to get a the language form an url. If you don't provide an url, it will default ot the curent one and thus use `$_SERVER['HTTP_HOST']`. It's strange that installing a language ends to this function. Could you provide a debug backtrace?

**Comment by Chouby** [comment]
According to https://make.wordpress.org/cli/handbook/common-issues/#php-notice-undefined-index-on-_server-superglobal, a default value should be set for `$_SERVER['HTTP_HOST']` in wp-config.php.

**Comment by szepeviktor** [comment]
@grappler Please consider using wp-cli.yml all the time.

```yaml
path: /home/USER/website/html/WP
url: http://SITENAME.TLD
debug: true
user: viktor
core update:
    locale: hu_HU
skip-plugins:
    # Version randomizer
    - better-wp-security
```
